# Generated by Django 5.0.1 on 2024-02-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('idconsumidor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('idemisor', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idespecie', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('abierto', models.BooleanField(default=False)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportarAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.CharField(max_length=6, null=True)),
                ('tipo_envio', models.CharField(max_length=1, null=True)),
                ('idresponsable', models.CharField(max_length=6, null=True)),
                ('idplanilla', models.CharField(max_length=3, null=True)),
                ('idemisor', models.CharField(max_length=3, null=True)),
                ('idturno', models.CharField(max_length=2, null=True)),
                ('fecha', models.CharField(blank=True, max_length=8, null=True)),
                ('idsucursal', models.CharField(max_length=3, null=True)),
                ('idespecie', models.CharField(max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Importar Asistencia',
                'verbose_name_plural': 'Importar Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idplanilla', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('idresponsable', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envio', models.CharField(blank=True, max_length=1)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idturno', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='idempresa',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ImportarAsistenciaDetalle',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('idcodigogeneral', models.CharField(max_length=8)),
                ('idactividad', models.CharField(max_length=3)),
                ('idlabor', models.CharField(max_length=6)),
                ('idconsumidor', models.CharField(max_length=6)),
                ('cantidad', models.FloatField()),
                ('importar_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='api.importarasistencia')),
            ],
            options={
                'unique_together': {('importar_asistencia', 'item')},
            },
        ),
    ]
